version: '3.7'

services:
  roulette-backend:
    image: nielshen/roulette:backend-latest
    ports:
      - "8080:8080"
    networks:
      - roulette-net
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - "JAVA_OPTS=-Dplay.http.secret.key=abcdefghijk"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "MONGO_URI=mongodb://mongo:27017/roulette"
      - "POSTGRES_URL=jdbc:postgresql://postgres:5432/roulette"
      - "POSTGRES_USER=roulette_user"
      - "POSTGRES_PASSWORD=roulette_pass"

  roulette-frontend:
    image: nielshen/roulette:frontend-latest
    ports:
      - "8081:8081"
    networks:
      - roulette-net
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    networks:
      - roulette-net
    environment:
      - POSTGRES_DB=roulette
      - POSTGRES_USER=poldi
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    networks:
      - roulette-net
    volumes:
      - mongo-data:/data/db

  db-client:
    image: ubuntu:20.04
    networks:
      - roulette-net
    volumes:
      - ./scripts:/scripts  # Ordner für MongoDB-Skripte
    tty: true
    stdin_open: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    entrypoint: /bin/bash
    command: >
      -c "apt-get update && apt-get install -y mongodb-clients postgresql-client && sleep infinity"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    networks:
      - roulette-net
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - roulette-net
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

volumes:
  postgres-data:
  mongo-data:

networks:
  roulette-net:
