name: Scala CI

on:
  push:
    branches: [ main, dev, devSA ]
  pull_request:
    branches: [ main, dev, devSA ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup
        run:
          sudo -i
          apt install curl -y
      - name: Run tests
        run:
          sbt clean test jacoco
      - name: Upload report to Codecov
        run: |
          curl -s https://codecov.io/bash > .codecov
          chmod +x .codecov
          bash .codecov
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ../
          file: /modules/controller/src/main/scala/Roulette/controller/Dockerfile
          push: true
          tags: nielshen/roulette:backend-latest
  
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ../
          file: /modules/userInterface/src/main/scala/Roulette/userInterface/Dockerfile
          push: true
          tags: nielshen/roulette:frontend-latest
